# Build the CV-Scope Windows installer.
#
#   powershell -ExecutionPolicy Bypass -File installer\build.ps1 [-SkipFrontend] [-Iscc <path to ISCC.exe>]
#
# Output: installer\build\output\CV-Scope-Setup-Windows-x64.exe and SHA256SUMS.txt
#
# Needs Node 20+ (for the web interface) and an internet connection. uv and,
# when ISCC.exe is not found, Inno Setup are downloaded into installer\build
# and checked against the SHA-256 in installer\pins.json. Nothing is installed
# system-wide. Python for drawing the icon comes from uv (with Pillow).

param(
    [switch]$SkipFrontend,
    [string]$Iscc = ""
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $here
$build = Join-Path $here "build"
$downloads = Join-Path $build "downloads"
New-Item -ItemType Directory -Force $build, $downloads, (Join-Path $build "tools") | Out-Null

function Step($msg) { Write-Host "`n== $msg" -ForegroundColor Cyan }

function Get-Verified($url, $sha256, $dest) {
    if ((Test-Path $dest) -and ((Get-FileHash $dest -Algorithm SHA256).Hash.ToLower() -eq $sha256)) { return }
    Write-Host "download $url"
    Invoke-WebRequest -Uri $url -OutFile "$dest.part" -UseBasicParsing
    $actual = (Get-FileHash "$dest.part" -Algorithm SHA256).Hash.ToLower()
    if ($actual -ne $sha256) {
        Remove-Item "$dest.part" -Force
        throw "SHA-256 mismatch for $url`n  expected $sha256`n  got      $actual"
    }
    Move-Item -Force "$dest.part" $dest
}

$pins = Get-Content (Join-Path $here "pins.json") -Raw | ConvertFrom-Json
$pyproject = Get-Content (Join-Path $root "backend\pyproject.toml") -Raw
if ($pyproject -notmatch '(?m)^version\s*=\s*"([^"]+)"') { throw "no version in backend\pyproject.toml" }
$version = $Matches[1]
Write-Host "CV-Scope $version, PyTorch $($pins.torch.version), uv $($pins.uv.version), Python $($pins.python)"

# ---------------------------------------------------------------- web interface
if ($SkipFrontend -and (Test-Path (Join-Path $root "frontend\dist\index.html"))) {
    Step "Web interface: using the existing frontend\dist"
} else {
    Step "Web interface (npm ci, npm run build)"
    Push-Location (Join-Path $root "frontend")
    try {
        npm ci --ignore-scripts --no-audit --no-fund
        if ($LASTEXITCODE -ne 0) { throw "npm ci failed" }
        npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed" }
    } finally { Pop-Location }
}

# ---------------------------------------------------------------- uv
Step "uv $($pins.uv.version)"
$uvZip = Join-Path $downloads "uv-$($pins.uv.version).zip"
Get-Verified $pins.uv.url $pins.uv.sha256 $uvZip
$uvDir = Join-Path $downloads "uv-$($pins.uv.version)"
if (-not (Test-Path (Join-Path $uvDir "uv.exe"))) { Expand-Archive -Force $uvZip $uvDir }
Copy-Item -Force (Join-Path $uvDir "uv.exe") (Join-Path $build "tools\uv.exe")
$uv = Join-Path $build "tools\uv.exe"

# ---------------------------------------------------------------- icon and wizard pictures
Step "Icon and wizard pictures"
$constraints = Get-Content (Join-Path $here "constraints.txt")
$pillow = ($constraints | Where-Object { $_ -match '^pillow==' }) | Select-Object -First 1
if (-not $pillow) { $pillow = "pillow" }
& $uv run --no-project --no-config --python $pins.python --with $pillow python (Join-Path $here "make_assets.py") $build
if ($LASTEXITCODE -ne 0) { throw "make_assets.py failed" }

# ---------------------------------------------------------------- pins for the script
Step "Pins (build\pins.iss, build\pins-code.iss)"
$defines = @(
    "; Generated by installer\build.ps1 from installer\pins.json. Do not edit.",
    "#define AppVersion `"$version`"",
    "#define PythonVersion `"$($pins.python)`"",
    "#define TorchVersion `"$($pins.torch.version)`"",
    "#define TorchvisionVersion `"$($pins.torch.torchvision)`""
)
$code = @(
    "{ Generated by installer\build.ps1 from installer\pins.json. Do not edit. }",
    "function Pin(const Key: String): String;",
    "begin"
)
$first = $true
foreach ($variant in $pins.torch.variants.PSObject.Properties) {
    foreach ($package in @("torch", "torchvision")) {
        $w = $variant.Value.$package
        foreach ($field in @(@("file", $w.file), @("url", $w.url), @("sha256", $w.sha256), @("size", [string]$w.size))) {
            if ($field[1] -match "'") { throw "unexpected quote in pins.json: $($field[1])" }
            $kw = if ($first) { "if" } else { "else if" }
            $code += "  $kw Key = '$($variant.Name).$package.$($field[0])' then Result := '$($field[1])'"
            $first = $false
        }
    }
}
$code += "  else RaiseException('Unknown pin ' + Key);"
$code += "end;"
Set-Content -Encoding ASCII -Path (Join-Path $build "pins.iss") -Value $defines
Set-Content -Encoding ASCII -Path (Join-Path $build "pins-code.iss") -Value $code

# ---------------------------------------------------------------- compiler
Step "Inno Setup"
if (-not $Iscc) {
    $candidates = @(
        (Join-Path $build "innosetup\ISCC.exe"),
        "${env:ProgramFiles(x86)}\Inno Setup 7\ISCC.exe",
        "$env:ProgramFiles\Inno Setup 7\ISCC.exe",
        "$env:LOCALAPPDATA\Programs\Inno Setup 7\ISCC.exe"
    )
    $Iscc = $candidates | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
}
if (-not $Iscc) {
    $setup = Join-Path $downloads "innosetup-$($pins.innosetup.version).exe"
    Get-Verified $pins.innosetup.url $pins.innosetup.sha256 $setup
    $dest = Join-Path $build "innosetup"
    # Portable mode: no uninstaller, Start-menu entry or file associations
    $p = Start-Process -FilePath $setup -ArgumentList "/PORTABLE=1", "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-", "/CURRENTUSER", "/DIR=`"$dest`"" -Wait -PassThru
    if ($p.ExitCode -ne 0) { throw "Inno Setup could not be unpacked (exit code $($p.ExitCode))" }
    $Iscc = Join-Path $dest "ISCC.exe"
}
Write-Host "compiler: $Iscc"

# ---------------------------------------------------------------- compile
Step "Compile"
& $Iscc "/Qp" (Join-Path $here "cvscope.iss")
if ($LASTEXITCODE -ne 0) { throw "ISCC failed with exit code $LASTEXITCODE" }

$exe = Join-Path $build "output\CV-Scope-Setup-Windows-x64.exe"
$hash = (Get-FileHash $exe -Algorithm SHA256).Hash.ToLower()
# The standard "<sha256>  <file>" format that sha256sum -c and the website read
[IO.File]::WriteAllText((Join-Path $build "output\SHA256SUMS.txt"), "$hash  CV-Scope-Setup-Windows-x64.exe`n", (New-Object Text.UTF8Encoding $false))
$size = "{0:N1} MB" -f ((Get-Item $exe).Length / 1MB)
Write-Host "`nBuilt $exe ($size)`nSHA-256 $hash" -ForegroundColor Green
